steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github.com/lkowalick/go-test-1:${COMMIT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/github.com/lkowalick/go-test-1:${COMMIT_SHA}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'go-test-1-service', '--image', 'gcr.io/${PROJECT_ID}/github.com/lkowalick/go-test-1:${COMMIT_SHA}', '--region', 'REGION']
options:
  logging: CLOUD_LOGGING_ONLY
images:
- gcr.io/${PROJECT_ID}/github.com/lkowalick/go-test-1:${COMMIT_SHA}